import type { Metadata } from "next";
import Mode from "./colorMode";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Frontend Mentor | REST Countries API",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/images/favicon.png",
        href: "/images/favicon.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={"/"}>
            <h1>Where in the world?</h1>
          </Link>
          <Mode />
        </header>
        {children}
      </body>
    </html>
  );
}
